Inmobiliaria/Models/FechasView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Inmobiliaria.Models
{
    public class FechasView
    {
        [Required]
        [DisplayName("Fecha Inicio"), DisplayFormat(DataFormatString = "{dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime FechaInicio { get; set; }
        [Required]
        [DisplayName("Fecha Cierre"), DisplayFormat(DataFormatString = "{dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime FechaCierre { get; set; }
        }
}

Inmobiliaria/Models/Inmueble.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Inmobiliaria.Models
{
    public class Inmueble
    {
       
        [Display(Name = "Código")]
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Campo obligatorio"),
        MinLength(5, ErrorMessage = "Mínimo 5 caracteres para dirección")]
        public string Direccion { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        public int Ambientes { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        public int Superficie { get; set; }

        [Required(ErrorMessage = "Campo obligatorio"),
        ForeignKey(nameof(PropietarioId))]
        [Display(Name = "Propietario")]
        public int PropietarioId { get; set; }


        [Display(Name = "Tipo")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string TipoInmueble { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        public decimal Precio { get; set; }
        public bool Disponible { get; set; } = true;

        [Display(Name = "Dueño")]
        public Propietario Duenio { get; set; }
       
    }
}

Inmobiliaria/Controllers/InmuebleController.cs
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace Inmobiliaria.Controllers
{
    public class InmuebleController : Controller
    {
        RepositorioInmueble repositorioInmueble;
        RepositorioPropietario repoPropietario;
        private readonly IConfiguration config;

        public InmuebleController(IConfiguration config)
        {
            this.config = config;
            repositorioInmueble = new RepositorioInmueble(config);
            repoPropietario = new RepositorioPropietario(config);
        }

        // GET: Inmueble
        [Authorize]
        public ActionResult Index()
        {

            try
            {
                var lista = repositorioInmueble.ObtenerTodos();
                ViewData[nameof(Inmueble)] = lista;
                ViewData["Tittle"] = nameof(Inmueble);
                ViewBag.Id = TempData["Id"];
                if (TempData.ContainsKey("Mensaje"))
                    ViewBag.Mensaje = TempData["Mensaje"];
                return View(lista);
            }
            catch (Exception ex)
            {

                Json(new { Error = ex.Message });
                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize]
        public ActionResult Disponibles()
        {
            IList<Inmueble> lista = repositorioInmueble.ObtenerDisponibles();
            return View(lista);
        }

        // GET: InmuebleController
        [HttpPost]
        [Authorize]
        public ActionResult Disponibles(FechasView f)
        {
            try {
                IList<Inmueble> lista = repositorioInmueble.ObtenerDisponiblesEntreFechas(f.FechaInicio,
                                                                                          f.FechaCierre);
                ViewBag.Fechas = f;
                TempData["FechaInicio"] = f.FechaInicio;
                TempData["FechaCierre"] = f.FechaCierre;

                return View(lista);
            }
            catch (Exception ex)
            {

                Json(new { Error = ex.Message });
                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize]
        public ActionResult Fechas()
        {
            return View();
        }

        [Authorize]
        public ActionResult PorPropietario(int id)
        {
            try
            {
                var lista = repositorioInmueble.BuscarPorPropietario(id);
                ViewData[nameof(Inmueble)] = lista;
                ViewData["Tittle"] = nameof(Inmueble);
                ViewBag.Id = TempData["Id"];
                if (TempData.ContainsKey("Mensaje"))
                    ViewBag.Mensaje = TempData["Mensaje"];
                return View(lista);
            }
            catch (Exception ex)
            {

                Json(new { Error = ex.Message });
                return RedirectToAction(nameof(Index));
            }
        }


        // GET: Inmueble/Details/5
        public ActionResult Details(int id)
        {
           
                var entidad = repositorioInmueble.ObtenerPorId(id);
                if (entidad == null) return RedirectToAction(nameof(Index));
                return View(entidad);

        }

        // GET: Inmueble/Create
        [Authorize]
        public ActionResult Crear()
        {
            ViewBag.Propietario = repoPropietario.Obtener();
            return View();
           
        }

        // POST: Inmueble/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Crear(Inmueble entidad)
        {
            try
            {
                repositorioInmueble.Alta(entidad);

                var res = entidad.Id;
                TempData["Id"] = res;
                TempData["Mensaje"] = $"Inmueble creado con éxito! Id: {res}";
                
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                ViewBag.StackTrate = e.StackTrace;
                return View(entidad);
            }
        }

        [Authorize]
        // GET: Inmueble/Edit/5
        public ActionResult Editar(int id)
        {

            var entidad = repositorioInmueble.ObtenerPorId(id);
            ViewBag.Propietarios = repoPropietario.Obtener();

            //if (entidad == null) return RedirectToAction(nameof(Index));
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(entidad);
          
            
        }

        // POST: Inmueble/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Editar(int id, Inmueble entidad)
        {
            try
            {
                entidad.Id = id;
                repositorioInmueble.Modificar(entidad);
                TempData["Mensaje"] = "Datos guardados correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Propietarios = repoPropietario.Obtener();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        // GET: Inmueble/Eliminar/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Eliminar(int id)
        {
            
                var entidad = repositorioInmueble.ObtenerPorId(id);
                if (TempData.ContainsKey("Mensaje"))
                    ViewBag.Mensaje = TempData["Mensaje"];
                if (TempData.ContainsKey("Error"))
                    ViewBag.Error = TempData["Error"];
                //if (entidad == null) return RedirectToAction(nameof(Index));
                return View(entidad);
           
        }

        // POST: Inmueble/Eliminar/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Eliminar(int id, Inmueble entidad)
        {
            try
            {
                repositorioInmueble.Baja(id);
                TempData["Mensaje"] = "Eliminación realizada correctamente";
                return RedirectToAction(nameof(Index));
            }
           
            catch (SqlException e)
            {
                if (e.Number == 547)
                {
                    TempData["Error"] = "No se pudo eliminar, está en uso.";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                TempData["Error"] = "Ocurrió un error inesperado.";
                return RedirectToAction(nameof(Index));
            }
        }
        }
    }

Inmobiliaria/Views/Inmueble/Crear.cshtml
@model Inmobiliaria.Models.Inmueble

@{
    ViewData["Title"] = "Crear";
    //List<Propietario> propietarios = ViewBag.Propietarios;
}

<h1>Crear nuevo</h1>

<h4>Inmueble</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Crear">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ambientes" class="control-label"></label>
                <input asp-for="Ambientes" class="form-control" />
                <span asp-validation-for="Ambientes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Superficie" class="control-label"></label>
                <input asp-for="Superficie" class="form-control" />
                <span asp-validation-for="Superficie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoInmueble" class="control-label"></label>
                <select asp-for="TipoInmueble" class="form-control">
                    <option value="No especificado">Seleccionar</option>
                    <option value="Casa">Casa</option>
                    <option value="Departamento">Departamento</option>
                    <option value="Local">Local</option>
                    <option value="Deposito">Depósito</option>
                </select>
                <span asp-validation-for="TipoInmueble" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <label class="control-label">Propietario</label>
                <select class="form-control" name="PropietarioId">
                    @foreach (var item in (List<Propietario>)ViewBag.Propietario)
                    {
                        <option value="@item.Id">@(item.Nombre + " " + item.Apellido)</option>
                    }
                </select>
                <span asp-validation-for="PropietarioId" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />

            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-outline-danger">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z" />
        </svg>
    </a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Inmobiliaria/Views/Inmueble/Disponibles.cshtml
@model IEnumerable<Inmobiliaria.Models.Inmueble>

@{
    ViewData["Title"] = "Inmuebles disponibles";

    bool esFechas = ViewData.ContainsKey("Fechas");
    FechasView fechas = esFechas ? ViewBag.Fechas : new FechasView();
    string entreFechas = " entre " + fechas.FechaInicio.ToString("dd/MM/yyyy") + " y " + fechas.FechaCierre.ToString("dd/MM/yyyy");

}

<h1><i class="bi bi-house-fill"></i>Inmuebles Disponibles@(esFechas ? entreFechas : "")</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ambientes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Superficie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoInmueble)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ambientes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Superficie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoInmueble)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                <a asp-controller="Contrato" asp-action="PorInmueble" asp-route-id="@item.Id">Contratos<i class="bi bi-calendar4-range"></i></a>
            <td>
                <a asp-controller="Contrato" asp-action="CrearPara" asp-route-id="@item.Id">Crear contrato<i class="bi bi-calendar4-range"></i></a>
            </td>
            </td>
            <td>
                @if (User.IsInRole("Administrador") || User.IsInRole("Empleado") || User.IsInRole("Propietario"))
                {
                    <a asp-action="Editar" asp-route-id="@item.Id" class="btn btn-outline-primary" title="Editar">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                            <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z" />
                        </svg>
                    </a>
                }
                @if (User.IsInRole("Administrador"))
                {
                    <a asp-action="Eliminar" asp-route-id="@item.Id" class="btn btn-outline-danger" title="Eliminar">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </a>
                }
            </td>
        </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Index" class="btn btn-outline-danger">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z" />
        </svg>
    </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Inmobiliaria/Views/Inmueble/Editar.cshtml
@model Inmobiliaria.Models.Inmueble

@{
    ViewData["Title"] = "Editar";
    List<Propietario> propietarios = ViewBag.Propietarios;
    
}

<h1>Editar</h1>

<h4>Inmueble</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ambientes" class="control-label"></label>
                <input asp-for="Ambientes" class="form-control" />
                <span asp-validation-for="Ambientes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Superficie" class="control-label"></label>
                <input asp-for="Superficie" class="form-control" />
                <span asp-validation-for="Superficie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoInmueble" class="control-label"></label>
                <select asp-for="TipoInmueble" class="form-control">
                    <option value="@Model.TipoInmueble " selected">@Model.TipoInmueble</option>
                    <option value="Casa">Casa</option>
                    <option value="Departamento">Departamento</option>
                    <option value="Monoambiente">Monoambiente</option>
                    <option value="Local">Local</option>
                </select>
                <span asp-validation-for="TipoInmueble" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Disponible" class="control-label"></label>
                <input asp-for="Disponible" class="form-control" />
                <span asp-validation-for="Disponible" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Propietario</label>
                <select class="form-control" name="PropietarioId">
                    @foreach (var item in propietarios)
                    {
                        @:<option @(item.Id == Model.PropietarioId ? "selected" : "") value="@item.Id">@(item.Nombre + " " + item.Apellido)</option>
                    }
                </select>
                <span asp-validation-for="PropietarioId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-outline-danger">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z" />
        </svg>
    </a>
</div>

Inmobiliaria/Views/Inmueble/Eliminar.cshtml
@model Inmobiliaria.Models.Inmueble

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>
<h3>¿Está seguro de querer eliminar este inmueble?</h3>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ambientes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ambientes)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Superficie)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Superficie)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoInmueble)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoInmueble)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PropietarioId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PropietarioId)
            @(Model.Duenio.Nombre + " " + Model.Duenio.Apellido)
        </dd>

    </dl>

    <form asp-action="Eliminar">
        <input type="submit" value="Confirmar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-outline-danger">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z" />
            </svg>
        </a>
    </form>
</div>

Inmobiliaria/Views/Inmueble/Fechas.cshtml
@model Inmobiliaria.Models.FechasView

@{
    ViewData["Title"] = "Fechas";
}

<h4>Verificar Fechas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Inmueble" asp-action="Disponibles">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaCierre" class="control-label"></label>
                <input asp-for="FechaCierre" class="form-control" />
                <span asp-validation-for="FechaCierre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ver disponibilidad" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}