Inmobiliaria/Models/LoginView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Inmobiliaria.Models
{
    public class LoginView
    {
        [DataType(DataType.EmailAddress)]
        public string Usuario { get; set; }
        [DataType(DataType.Password)]
        public string Clave { get; set; }
    }
}

Inmobiliaria/Controllers/GaranteController.cs
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace Inmobiliaria.Controllers
{
    public class GaranteController : Controller
    {
        private readonly IConfiguration config;
        RepositorioGarante repositorioGarante;
        RepositorioContrato repositorioContrato;

        public GaranteController(IConfiguration config)
        {
            this.config = config;
            repositorioGarante = new RepositorioGarante(config);
            repositorioContrato = new RepositorioContrato(config);
        }

        // GET: Garante
        public ActionResult Index()
        {
            try
            {
                var lista = repositorioGarante.Obtener();
                ViewData[nameof(Garante)] = lista;
                ViewData["Tittle"] = nameof(Garante);
                ViewBag.Id = TempData["Id"];
                if (TempData.ContainsKey("Mensaje"))
                    ViewBag.Mensaje = TempData["Mensaje"];
                return View(lista);
            }
            catch (Exception ex)
            {

                Json(new { Error = ex.Message });
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: Garante/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Garante/Create
        public ActionResult Crear()
        {
            return View();
        }

        // POST: Garante/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Crear(Garante garante)
        {
            try
            {
                int res = repositorioGarante.Alta(garante);
                TempData["Id"] = garante.Id;
                TempData["Mensaje"] = $"Garante creado con éxito! Id: {res}";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return RedirectToAction(nameof(Crear));
            }
        }

        // GET: Garante/Edit/5
        [Authorize]
        public ActionResult Editar(int id)
        {
            var garante = repositorioGarante.ObtenerGarante(id);
            return View(garante);
        }

        // POST: Garante/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(int id, IFormCollection collection)
        {
            try
            {
                Garante garante = repositorioGarante.ObtenerGarante(id);
                garante.Nombre = collection["Nombre"];
                garante.Dni = collection["Dni"];
                garante.Telefono = collection["Telefono"];
                

                repositorioGarante.Modificar(garante);

                TempData["Mensaje"] = "Datos guardados correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(null);
            }
        }

        // GET: Garante/Delete/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Eliminar(int id)
        {
            try
            {
                var entidad = repositorioGarante.ObtenerGarante(id);
                if (TempData.ContainsKey("Mensaje"))
                    ViewBag.Mensaje = TempData["Mensaje"];
                if (TempData.ContainsKey("Error"))
                    ViewBag.Error = TempData["Error"];
                return View(entidad);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Eliminar(int id, Garante entidad)
        {
            try
            {
                repositorioGarante.Baja(id);
                TempData["Mensaje"] = "Eliminación realizada correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (SqlException e)
            {
                if (e.Number == 547)
                {
                    TempData["Error"] = "No se pudo eliminar, está en uso.";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                TempData["Error"] = "Ocurrió un error inesperado.";
                return RedirectToAction(nameof(Index));
            }

        }
    }
}

Inmobiliaria/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Inmobiliaria.Data;
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using System.IO;
using Microsoft.VisualBasic.FileIO;

namespace Inmobiliaria.Controllers
{
    public class UsuarioController : Controller
    {
        RepositorioUsuario repositorio;
        private readonly IConfiguration configuration;
        private readonly IWebHostEnvironment environment;

        public UsuarioController(RepositorioUsuario repositorio, IWebHostEnvironment environment, IConfiguration configuration)
        {
            this.repositorio = repositorio;
            this.environment = environment;
            this.configuration = configuration;
        }

        // GET: UsuarioController
        [Authorize(Policy = "Administrador")]
        public ActionResult Index()
        {
            IList<Usuario> lista = repositorio.ObtenerTodos();
            return View(lista);
        }

        // GET: UsuarioController/Create
        [Authorize(Policy = "Administrador")]
        public ActionResult Crear()
        {
            ViewBag.Roles = Usuario.ObtenerRoles();
            return View();
        }

        // POST: UsuarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Crear(Usuario ent)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                        password: ent.Clave,
                        salt: System.Text.Encoding.ASCII.GetBytes(configuration["Salt"]),
                        prf: KeyDerivationPrf.HMACSHA1,
                        iterationCount: 1000,
                        numBytesRequested: 256 / 8));
                ent.Clave = hashed;
                ent.Avatar = "/uploads/avatarDefault.png";

                int res = repositorio.Alta(ent);
                if (ent.AvatarFile != null && ent.Id > 0)
                {
                    string path = Path.Combine(environment.WebRootPath, "uploads");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    string fileName = "avatar" + ent.Id + Path.GetExtension(ent.AvatarFile.FileName);
                    string pathCompleto = Path.Combine(path, fileName);
                    using (FileStream stream = new FileStream(pathCompleto, FileMode.Create))
                    {
                        ent.AvatarFile.CopyTo(stream);
                    }
                    ent.Avatar = Path.Combine("/uploads", fileName);

                    repositorio.Alta(ent);
                }
                TempData["Mensaje"] = $"Usuario creado con éxito! Id: {res}";
                return RedirectToAction(nameof(Index));
            }
            catch (SqlException e)
            {
                TempData["Error"] = e.Number + " " + e.Message;
                ViewBag.Roles = Usuario.ObtenerRoles();
                return View();
            }
            catch (Exception)
            {
                TempData["Error"] = "Ocurrió un error inesperado.";
                ViewBag.Roles = Usuario.ObtenerRoles();
                return View();
            }
        }

        // GET: UsuarioController/Edit/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Editar(int id)
        {
            var ent = repositorio.Obtener(id);
            if (ent == null) return RedirectToAction(nameof(Index));
            ViewBag.Roles = Usuario.ObtenerRoles();
            return View(ent);
        }

        // GET: UsuarioController/EditarPerfil
        [Authorize(Policy = "Administrador")]
        public ActionResult EditarPerfil()
        {
            var ent = repositorio.ObtenerPorEmail(User.Identity.Name);
            ViewBag.Roles = Usuario.ObtenerRoles();
            return View("Editar", ent);
        }

        // POST: UsuarioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Editar(int id, Usuario ent)
        {
            try
            {
                
                    var usuarioActual = repositorio.ObtenerPorEmail(User.Identity.Name);
                    if (usuarioActual.Id != id)//si no es admin, solo puede modificarse él mismo
                        return RedirectToAction(nameof(Index), "Home");
                
                string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                        password: ent.Clave,
                        salt: System.Text.Encoding.ASCII.GetBytes(configuration["Salt"]),
                        prf: KeyDerivationPrf.HMACSHA1,
                        iterationCount: 1000,
                        numBytesRequested: 256 / 8));
                ent.Clave = hashed;
                ent.Rol = User.IsInRole("Administrador") ? ent.Rol : (int)rol.Empleado;
                var entOriginal = repositorio.Obtener(id);
                ent.Avatar = entOriginal.Avatar;
                if (ent.AvatarFile != null)
                {
                    string path = Path.Combine(environment.WebRootPath, "uploads");
                    if (Path.GetFileName(ent.Avatar) != "avatarDefault.png")
                    {
                        if (FileSystem.FileExists(Path.Combine(path, Path.GetFileName(ent.Avatar))))
                            FileSystem.DeleteFile(Path.Combine(path, Path.GetFileName(ent.Avatar)));
                    }
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    string fileName = "avatar" + ent.Id + Path.GetExtension(ent.AvatarFile.FileName);
                    string pathCompleto = Path.Combine(path, fileName);
                    using (FileStream stream = new FileStream(pathCompleto, FileMode.Create))
                    {
                        ent.AvatarFile.CopyTo(stream);
                    }
                    ent.Avatar = Path.Combine("/uploads", fileName);
                }

                repositorio.Modificacion(ent);

                if (!User.IsInRole("Administrador"))
                {
                    return RedirectToAction(nameof(Perfil));
                }
                else
                {
                    TempData["Mensaje"] = "Usuario modificado con éxito!";
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (SqlException e)
            {
                TempData["Error"] = e.Number + " " + e.Message;
                ViewBag.Roles = Usuario.ObtenerRoles();
                return View(ent);
            }
            catch (Exception)
            {
                TempData["Error"] = "Ocurrió un error inesperado.";
                ViewBag.Roles = Usuario.ObtenerRoles();
                return View(ent);
            }
        }

        // GET: UsuarioController/Delete/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Baja(int id)
        {
            var ent = repositorio.Obtener(id);
            if (ent == null) return RedirectToAction(nameof(Index));
            return View(ent);
        }

        // POST: UsuarioController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Baja(int id, Usuario ent)
        {
            try
            {
               string filename = Path.GetFileName((string) TempData["AvatarPath"]);
                repositorio.Baja(id);
                if (filename != "avatarDefault.png")
                {
                    if (FileSystem.FileExists(Path.Combine(environment.WebRootPath, "uploads", filename)))
                        FileSystem.DeleteFile(Path.Combine(environment.WebRootPath, "uploads", filename));
                }
                TempData["Mensaje"] = "Usuario eliminado con éxito!";
                return RedirectToAction(nameof(Index));
            }
            catch (SqlException e)
            {
                if (e.Number == 547)
                {
                    TempData["Error"] = "No se pudo eliminar, está en uso.";
                }
                return RedirectToAction(nameof(Index)); ;
            }
            catch (Exception)
            {
                TempData["Error"] = "Ocurrió un error inesperado.";
                return RedirectToAction(nameof(Index)); ;
            }
        }

       
        // GET: UsuarioController/Login/
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<ActionResult> Login(LoginView login)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                        password: login.Clave,
                        salt: System.Text.Encoding.ASCII.GetBytes(configuration["Salt"]),
                        prf: KeyDerivationPrf.HMACSHA1,
                        iterationCount: 1000,
                        numBytesRequested: 256 / 8));

                    var ent = repositorio.ObtenerPorEmail(login.Usuario);

Inmobiliaria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link href="~/css/main.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    <link rel="icon" href="~/img/favicon.png" type="image/x-icon" />

    <script src="https://unpkg.com/mustache@latest"></script>

    <!--<link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    <link rel="icon" href="~/img/favicon.png" type="image/x-icon" />
     Posibles estilos a aplicar. False porque es opcional. La página que lo necesita, declara la sección.-->
    @RenderSection("Styles", false)


    <title>@ViewData["Title"] - Inmobiliaria Herrera @DateTime.Today.Year</title>
    

</head>
<body onload="init()">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand  " asp-area="" asp-controller="Home" asp-action="Index">Inmobiliaria Herrera</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                    @if (User.IsInRole("Administrador"))
                                    {

                                        <div class="dropdown ml-1 mr-1">
                                            <button class="btn btn-outline-dark dropdown-toggle"
                                                    type="button" id="dropdownMenu1" data-toggle="dropdown"
                                                    aria-haspopup="true" aria-expanded="false">
                                                <i class="bi bi-file-person">Usuarios</i>
                                            </button>
                                            <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Lista</a>
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Crear">Crear</a>
                                            </div>
                                        </div>
                                    }

                                    <div class="dropdown ml-1 mr-1">
                                        <button class="btn btn-outline-dark dropdown-toggle"
                                                type="button" id="dropdownMenu1" data-toggle="dropdown"
                                                aria-haspopup="true" aria-expanded="false">
                                            <i class="bi bi-file-person">Propietarios</i>
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Propietario" asp-action="Index">Lista</a>
                                            @if (User.IsInRole("Administrador") || User.IsInRole("Empleado"))
                                            {
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Propietario" asp-action="Crear">Crear</a>
                                            }
                                            </div>
                                    </div>

                                    <div class="dropdown ml-1 mr-1">
                                        <button class="btn btn-outline-dark dropdown-toggle"
                                                type="button" id="dropdownMenu1" data-toggle="dropdown"
                                                aria-haspopup="true" aria-expanded="false">
                                            <i class="bi bi-house-fill">Inmuebles</i>
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Inmueble" asp-action="Index">Lista</a>
                                            @if (User.IsInRole("Administrador") || User.IsInRole("Empleado") || User.IsInRole("Propietario"))
                                            {
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Inmueble" asp-action="Crear">Crear</a>
                                            }

                                            <a class="nav-link text-dark" asp-area="" asp-controller="Inmueble" asp-action="Disponibles" class="btn btn-light">
                                                Disponibles
                                            </a>
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Inmueble" asp-action="Fechas">Disp. entre Fechas</a>
                                        </div>
                                    </div>
                                    <div class="dropdown ml-1 mr-1">
                                        <button class="btn btn-outline-dark dropdown-toggle"
                                                type="button" id="dropdownMenu1" data-toggle="dropdown"
                                                aria-haspopup="true" aria-expanded="false">
                                            <i class="bi bi-file-person">Inquilinos</i>
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Inquilino" asp-action="Index">Lista</a>

                                            @if (User.IsInRole("Administrador") || User.IsInRole("Empleado"))
                                            {
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Inquilino" asp-action="Crear">Crear</a>
                                            }
                                            

                                        </div>
                                    </div>

                                    <div class="dropdown ml-1 mr-1">
                                        <button class="btn btn-outline-dark dropdown-toggle"
                                                type="button" id="dropdownMenu1" data-toggle="dropdown"
                                                aria-haspopup="true" aria-expanded="false">
                                            <i class="bi bi-calendar4-range">Contratos</i>
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            <a class="dropdown-item text-dark" asp-area="" asp-controller="Contrato" asp-action="Index">Lista</a>
                                            <a class="dropdown-item text-dark" asp-area="" asp-controller="Contrato" asp-action="Vigentes">Vigentes</a>
                                        </div>
                                    </div>
                                    <div class="dropdown ml-1 mr-1">
                                        <button class="btn btn-outline-dark dropdown-toggle"
                                                type="button" id="dropdownMenu1" data-toggle="dropdown"
                                                aria-haspopup="true" aria-expanded="false">
                                            <i class="bi bi-file-person">Garantes</i>
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            <a class="dropdown-item text-dark" asp-area="" asp-controller="Garante" asp-action="Index">Lista</a>

                                            @if (User.IsInRole("Administrador") || User.IsInRole("Empleado"))
                                            {
                                            <a class="dropdown-item text-dark" asp-area="" asp-controller="Garante" asp-action="Crear">Crear</a>
                                            }
                                        </div>
                                    </div>
                                </ul>
                            </div>
                        }
                        <ul class="navbar-nav text-right">
                            <li class="nav-item">

                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <div class="dropdown ml-1 mr-1">
                                        <button class="btn btn-outline-dark dropdown-toggle"
                                                type="button" id="dropdownMenu1" data-toggle="dropdown"
                                                aria-haspopup="true" aria-expanded="false">
                                            Iniciar sesión
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Acceder</a>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="dropdown">
                                        <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            @User.Identity.Name
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <a class="dropdown-item text-danger" asp-area="" asp-controller="Usuario" asp-action="Logout"><i class="bi bi-box-arrow-right"></i>Salir</a>
                                        </div>
                                    </div>
                                }
                            </li>
                        </ul>
                </div>
        </nav>
    </header>
    <div class="container">
        <div class="">
           
            <div class="m-1 p-1">
                @RenderBody()
                </main>
            </div>

            <footer class="border-top footer text-muted">
                <div class="container">
                    <p class="text-center"> @ViewData["Title"] - Inmobiliaria Herrera @DateTime.Today.Year </p>
                </div>
            </footer>
            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Inmobiliaria/Views/Shared/_Login.cshtml
@model Inmobiliaria.Models.LoginView

<h1 class="text-center">Acceder</h1>
<hr />
<div class="row">
    <div class="col-md-4 mx-auto">
        <form asp-controller="Usuario" asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Usuario" class="control-label"></label>
                <input asp-for="Usuario" class="form-control" />
                <span asp-validation-for="Usuario" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Clave" class="control-label"></label>
                <input asp-for="Clave" class="form-control" />
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>

            <div class="form-group text-center">
                <input type="submit" value="Iniciar Sesion" class="btn btn-outline-dark text-center" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Inmobiliaria/Views/Shared/_ScriptsPartial.cshtml
<script src="~/lib/jquery/jquery.js"></script>
<script src="https://cdn.linearicons.com/free/1.0.0/svgembedder.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>