Inmobiliaria/Controllers/ContratoController.cs
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace Inmobiliaria.Controllers
{
    public class ContratoController : Controller
    {
        RepositorioContrato repositorioContrato;
        RepositorioInquilino repositorioInquilino;
        RepositorioInmueble repositorioInmueble;
        RepositorioGarante repositorioGarante;
        RepositorioPago repositorioPago;
        private readonly IConfiguration configuration;
       

        public ContratoController(IConfiguration configuration)
        {
            this.configuration = configuration;
            repositorioInmueble = new RepositorioInmueble(configuration);
            repositorioInquilino = new RepositorioInquilino(configuration);
            repositorioContrato = new RepositorioContrato(configuration);
            repositorioGarante = new RepositorioGarante(configuration);
            repositorioPago = new RepositorioPago(configuration);
        }

        // GET: ContratoController
        [Authorize]
        public ActionResult Index()
        {
            try
            {
                //ViewBag.Estados = Contrato.ObtenerEstados();
                List<Contrato> lista = repositorioContrato.ObtenerTodos();
                //ViewData[nameof(Contrato)] = lista;
                //ViewData["Tittle"] = nameof(Contrato);
                //ViewBag.Id = TempData["Id"];
                //if (TempData.ContainsKey("Mensaje"))
                  //  ViewBag.Mensaje = TempData["Mensaje"];
                return View(lista);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(nameof(Index));
            }
        }
        [Authorize]
        public ActionResult PorInmueble(int id)
        {
            try
            {
                List<Contrato> lista = repositorioContrato.ObtenerPorInmueble(id);
                Inmueble ent = repositorioInmueble.ObtenerPorId(id);
                if (ent == null) return RedirectToAction(nameof(Index));
                ViewBag.PorInmueble = ent;
                return View("Index", lista);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(nameof(Index));
            }
        }
        [Authorize]
        public ActionResult Vigentes()
        {
            IList<Contrato> lista = repositorioContrato.ObtenerVigentes();
            ViewBag.Cancelar = true;
            return View(lista);
        }

        // GET: ContratoController/ConfirmarCancelar
        [Authorize]
        public ActionResult Cancelar(int id)
        {
            
            try
            {
                var ent = repositorioContrato.ObtenerContrato(id);

                var numPagos = repositorioPago.ObtenerPorContrato(ent.Id).Count;
                if (numPagos > 0)
                {
                    var nummeses = ent.CalcularMeses();

                    var debe = nummeses - numPagos;

                    ViewBag.Debe = debe;
                }

                if (ent == null) return RedirectToAction(nameof(Index));

                return View(ent);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(nameof(Index));
            }
        }

        // POST: ContratoController/ConfirmarCancelar
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Cancelar(int id, Contrato ent)
        {
            
        try 
        {
            repositorioContrato.Cancelar(id);
                
                TempData["Mensaje"] = "Contrato cancelado con éxito!";
                return View(nameof(Vigentes));
            }
            catch (Exception ex)
            {

                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(nameof(Index));
            }
        }
        [Authorize]
        public ActionResult Renovar(int id)
        {
            try
            {
                Contrato prev = repositorioContrato.ObtenerContrato(id);

                Contrato contrato = new Contrato
                {
                    FechaInicio = prev.FechaCierre,
                    FechaCierre = prev.FechaCierre.AddMonths(24),
                    Precio = prev.Inmueble.Precio
                };
                ViewBag.Inmueble = repositorioInmueble.ObtenerPorId(prev.InmuebleId);
                ViewBag.Inquilino = repositorioInquilino.ObtenerInquilino(prev.InquilinoId);
                
                return View(contrato);

            }
            catch (Exception ex)
            {
                
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(nameof(Index));
            }
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Renovar(int id, Contrato contrato)
        {
           try
            {
                if (contrato.FechaInicio < contrato.FechaCierre)
                {

                    contrato.Id = id;
                    repositorioContrato.Renovar(contrato);
                    var res = contrato.Id;
                    TempData["Mensaje"] = "Datos guardados correctamente";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Error"] = "Error, no se puede renovar el contrato con esa fecha de cierre";
                    return RedirectToAction(nameof(Index));
                }
                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                    ViewBag.StackTrate = e.StackTrace;
                    return View(contrato);
                }

         }


        // GET: ContratoController/Crear
        [Authorize]
        public ActionResult Crear()
        {
            ViewBag.Inquilinos = repositorioInquilino.Obtener();
            ViewBag.Inmuebles = repositorioInmueble.ObtenerTodos();
            ViewBag.Garantes = repositorioGarante.Obtener();
            ViewBag.FechaInicio = DateTime.Now;
            return View();
        }

        [Authorize]
        public ActionResult CrearPara(int id)
        {
            try
            {
            ViewBag.Inquilinos = repositorioInquilino.Obtener();
            ViewBag.Garantes = repositorioGarante.Obtener();
            ViewBag.Inmuebles = repositorioInmueble.ObtenerTodos();
            
           //Inmueble inmueble = repositorioInmueble.ObtenerPorId(id);
                ViewBag.InmuebleId = id;

                ViewBag.FechaInicio = TempData.ContainsKey("FechaInicio") ? TempData["FechaInicio"] : DateTime.Now;
            ViewBag.FechaFinal = TempData.ContainsKey("FechaFinal") ? TempData["FechaFinal"] : DateTime.Now.AddMonths(24);

                return View(nameof(Crear));
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                ViewBag.StackTrate = e.StackTrace;
                return View(nameof(Index));
            }
        }

        // POST: ContratoController/Crear
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Contrato ent)
        {
                    
            try
                {
                //ViewBag.Estados = Contrato.ObtenerEstados();
                repositorioContrato.Alta(ent);

                        int res = ent.Id;
                        TempData["Id"] = res;
                        TempData["Mensaje"] = $"Contrato creado con éxito! Id: {res}";
                        return RedirectToAction(nameof(Index));
                    
                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                    ViewBag.StackTrate = e.StackTrace;
                    return View(ent);
                }
        }


        // GET: ContratoController/Edit/5
        [Authorize]
        public ActionResult Editar(int id)
        {
            //ViewBag.Estados = Contrato.ObtenerEstados();
            try
            {
                var contrato = repositorioContrato.ObtenerContrato(id);
                ViewBag.Contrato = contrato;
                //ViewBag.Inquilinos = repositorioInquilino.Obtener();
                //ViewBag.Inmuebles = repositorioInmueble.ObtenerTodos();
                ViewBag.Garantes = repositorioGarante.Obtener();

                if (TempData.ContainsKey("Mensaje"))
                    ViewBag.Mensaje = TempData["Mensaje"];
                if (TempData.ContainsKey("Error"))
                    ViewBag.Error = TempData["Error"];
                return View(contrato);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(nameof(Index));
            }
        }

        // POST: ContratoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Editar(int id, Contrato ent)
        {
            
            try
            {
                repositorioContrato.Modificar(ent);
                TempData["Mensaje"] = "Contrato modificado con éxito!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

Inmobiliaria/Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Inmobiliaria.Data;
using Inmobiliaria.Models;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Authorization;

namespace Inmobiliaria.Controllers
{
    public class PagoController : Controller
    {
        RepositorioContrato repositorioContrato;
        RepositorioPago repositorioPago;
        private readonly IConfiguration config;

        public PagoController(IConfiguration config )
        {
            this.config = config;
            repositorioContrato = new RepositorioContrato(config);
            repositorioPago = new RepositorioPago(config);
        }

        // GET: Pago
        [Authorize]
        public ActionResult Index()
        {
            try
            {
                var lista = repositorioPago.ObtenerTodos();
                ViewData[nameof(Pago)] = lista;
                ViewData["Tittle"] = nameof(Pago);
                ViewBag.Id = TempData["Id"];
                if (TempData.ContainsKey("Mensaje"))
                    ViewBag.Mensaje = TempData["Mensaje"];
                return View(lista);
            }
            catch (Exception ex)
            {

                Json(new { Error = ex.Message });
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: PorContrato

        [Authorize]
        public ActionResult PorContrato(int id)
        {
            
                try
                { 
                    IList<Pago> lista = repositorioPago.ObtenerPorContrato(id);
                    ViewBag.Contrato = repositorioContrato.ObtenerContrato(id);
                    ViewBag.ContratoId = id;
                    return View("Index", lista);
                }
                catch (Exception ex)
                {

                    Json(new { Error = ex.Message });
                    return RedirectToAction(nameof(Index));
                }
            
        }

        // GET: Pago/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {

            var entidad = repositorioPago.ObtenerPorId(id);
            ViewBag.NumeroPago = entidad.ObtenerPago();
            if (entidad == null) return RedirectToAction(nameof(Index));
            return View(entidad);

        }

        // GET: Pago/Crear
        [Authorize]
        public ActionResult Crear(int id)
        {
           try {
                ViewBag.Contrato = repositorioContrato.ObtenerContrato(id);
                return View();
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                ViewBag.StackTrate = e.StackTrace;
                return View();
            }

        }

        // POST: Pago/Crear
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Crear(int id, Pago entidad)
        {
            try
            {
                entidad.Id = id;
                repositorioPago.Alta(entidad);

                TempData["Id"] = id;
                TempData["Mensaje"] = $"Pago realizado con éxito! Id: {id}";

                var list = repositorioPago.ObtenerPorContrato(entidad.ContratoId);
                ViewBag.Contrato = repositorioContrato.ObtenerContrato(id);
                ViewBag.ContratoId = id;
                return View("Index", list);
                
            }
            catch (SqlException e)
            {
                TempData["Error"] = e.Number + " " + e.Message;
                ViewBag.Contratos = repositorioContrato.ObtenerTodos();
                return View();
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                ViewBag.StackTrate = e.StackTrace;
                return View(entidad);
            }
        }

        // GET: Pago/Edit/5
        [Authorize]
        public ActionResult Editar(int id)
        {

            var entidad = repositorioPago.ObtenerPorId(id);
            ViewBag.Pago = entidad;

            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(entidad);

        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Editar(int id, Pago entidad)
        {
            try
            {
                entidad.Id = id;
                repositorioPago.Modificar(entidad);
                TempData["Mensaje"] = "Datos guardados correctamente";

                var list = repositorioPago.ObtenerPorContrato(entidad.ContratoId);
                ViewBag.Contrato = repositorioContrato.ObtenerContrato(entidad.ContratoId);
                ViewBag.ContratoId = entidad.ContratoId;

                return View("Index", list);
            }
            catch (SqlException e)
            {
                TempData["Error"] = e.Number + " " + e.Message;
                ViewBag.Contratos = repositorioContrato.ObtenerTodos();
                return View(entidad);
            }
            catch (Exception ex)
            {
                ViewBag.Contratos = repositorioContrato.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        // GET: Pago/Delete/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Eliminar(int id)
        {

            var entidad = repositorioPago.ObtenerPorId(id);
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            //if (entidad == null) return RedirectToAction(nameof(Index));
            return View(entidad);

        }

        // POST: Pago/Delete/5
       
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Eliminar(int id, Pago entidad)
        {
            try
            {
                repositorioPago.Baja(id);
                TempData["Mensaje"] = "Eliminación realizada correctamente";
                return RedirectToAction(nameof(Index));
            }

            catch (SqlException e)
            {
                if (e.Number == 547)
                {
                    TempData["Error"] = "No se pudo eliminar, está en uso.";
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                TempData["Error"] = "Ocurrió un error inesperado.";
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Inmobiliaria/Views/Contrato/Eliminar.cshtml
@model Inmobiliaria.Models.Contrato

@{
    ViewData["Title"] = "Eliminar";
    Inmueble inmueble = (Inmueble)ViewBag.Inmueble;
}

<h1>Eliminar</h1>
<h3>¿Está seguro de querer eliminar este contrato?</h3>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.InmuebleId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InmuebleId)
            @Html.DisplayFor(model => model.Inmueble.Direccion)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.InquilinoId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InquilinoId)
            @Html.DisplayFor(model => model.Inquilino.Apellido)
            @Html.DisplayFor(model => model.Inquilino.Nombre)
        </dd>
    </dl>

    <form asp-action="Eliminar">
        <input type="submit" value="Confirmar" class="btn btn-danger" /> |
             <a asp-action="Index" class="btn btn-outline-danger">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z" />
                </svg>
            </a>
    </form>
</div>

Inmobiliaria/Views/Contrato/Index.cshtml
@model IEnumerable<Inmobiliaria.Models.Contrato>

@{
    ViewData["Title"] = "Contratos";
    //List<Contrato> contratos = ViewData[nameof(Contrato)] as List<Contrato>;
    string mensaje = TempData["Mensaje"] + "";
    string error = TempData["Error"] + "";

}

<h1>CONTRATOS</h1>
@if (mensaje.Length != 0)
{
    <div class="alert alert-dismissible alert-success">
        @mensaje
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
}
@if (error.Length != 0)
{
    <div class="alert alert-dismissible alert-warning">
        @error
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
}

<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.FechaInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaCierre)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.InmuebleId) <i class="bi bi-house-fill"></i>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InquilinoId) <i class="bi bi-file-person"></i>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GaranteId)
            </th>
            
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaCierre)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.InmuebleId)
                @(item.Inmueble.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InquilinoId)
                @(item.Inquilino.Nombre + " " + item.Inquilino.Apellido)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GaranteId)
                @(item.Garante.Nombre)
            </td>
           
            <td>
                <a asp-controller="Pago" asp-action="PorContrato" asp-route-id="@item.Id">Pagos <i class="bi bi-credit-card-fill"></i></a>
            </td>
            <td>
                <span>
                    @if (User.IsInRole("Administrador") || User.IsInRole("Empleado"))
                    {
                        <a asp-action="Editar" asp-route-id="@item.Id" class="btn btn-outline-primary" title="Editar">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z" />
                            </svg>
                        </a>
                    }

                    @if (item.EsVigente && (User.IsInRole("Administrador") || User.IsInRole("Empleado")))
                    {
                        <a asp-action="Cancelar" asp-route-id="@item.Id" class="btn btn-outline-danger" title="Cancelar">
                        <i class="bi bi-x-square-fill text-danger"></i></a>
                    }
                    @if (User.IsInRole("Administrador"))
                    {
                        <a asp-action="Eliminar" asp-route-id="@item.Id" class="btn btn-outline-danger" title="Eliminar">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                            </svg>
                        </a>
                    }
                    @if (item.FechaCierre <= DateTime.Now)
                    {
                        <hr />
                        <a asp-action="Renovar" asp-route-id="@item.Id"><i class="bi bi-calendar2-plus-fill text-success"> Renovar Contrato </i></a>
                    }
                </span>
            </td>
        </tr>
        }
    </tbody>
</table>

Inmobiliaria/Views/Contrato/Vigentes.cshtml
@model IEnumerable<Inmobiliaria.Models.Contrato>

@{
    ViewData["Title"] = "Contratos Vigentes";
    bool esPorInm = ViewData.ContainsKey("PorInmueble");
    Inmueble inmu = ViewBag.PorInmueble ?? new Inmueble();
}

<table class="table">
    <thead>
        <tr>
            <th width="60px">
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaInicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaCierre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InquilinoId)  <i class="bi bi-file-person"></i>
            </th>
            @if (!esPorInm)
            {
                <th>
                    @Html.DisplayNameFor(model => model.InmuebleId)  <i class="bi bi-house-fill"></i>
                </th>
            }
            <th>
                @Html.DisplayNameFor(model => model.EsVigente)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaCierre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Inquilino.Nombre) @Html.DisplayFor(modelItem => item.Inquilino.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Inmueble.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EsVigente)
            </td>
            <td>
                <a asp-controller="Pago" asp-action="PorContrato" asp-route-id="@item.Id">Pagos <i class="bi bi-credit-card-fill"></i></a>
            </td>
            <td>

                <span>
                    @if (User.IsInRole("Administrador") || User.IsInRole("Empleado"))
                    {
                        <a asp-action="Editar" asp-route-id="@item.Id" class="btn btn-outline-primary" title="Editar">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z" />
                            </svg>
                        </a>
                    }

                    @if (item.EsVigente && (User.IsInRole("Administrador") || User.IsInRole("Empleado")))
                    {
                        <a asp-action="Cancelar" asp-route-id="@item.Id" class="btn btn-outline-danger" title="Cancelar">
                            <i class="bi bi-x-square-fill text-danger"></i>
                        </a>
                    }
                    @if (User.IsInRole("Administrador"))
                    {
                        <a asp-action="Eliminar" asp-route-id="@item.Id" class="btn btn-outline-danger" title="Eliminar">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                            </svg>
                        </a>
                    }
                </span>
            </td>
        </tr>
        }
    </tbody>
</table>